USE sakila;

-- List the number of films per category

-- film_category 
SELECT f.category_id, count(*) AS number_of_movies
from film_category f
JOIN film
ON f.film_id = film.film_id
GROUP BY f.category_id;

-- Retrieve the store ID, city, and country for each store.

-- store-address using addres id
-- address - citz using city id
-- city - country using country id

SELECT s.store_id, c.city, co.country
FROM store s
JOIN address a
ON a.address_id = s.address_id
JOIN city c
ON c.city_id = a.city_id
JOIN country co
ON c.country_id = co.country_id;

-- Calculate the total revenue generated by each store in dollars

-- rental-payment on rental_id
-- payment-customer on customer_id
-- store-customer on store_id

SELECT s.store_id, SUM(p.amount)
FROM store s
JOIN customer c
ON s.store_id = c.store_id
JOIN payment p
ON c.customer_id = p.customer_id
JOIN rental r
ON r.rental_id = p.payment_id
GROUP BY s.store_id;

-- Determine the average running time of films for each category.

SELECT c.name, AVG(f.length)
FROM category c
JOIN film_category fc
ON c.category_id = fc.category_id
JOIN film f
ON fc.film_id = f.film_id
GROUP BY c.name;



